name: "Terraform LocalStack CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-deploy:
    name: "Terraform Init, Plan & Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Sobe o LocalStack usando a Action oficial (muito mais estável no CI)
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          services: "s3"
          install-awslocal: false

      # 2. Configura a CLI do Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # 3. Comandos do Terraform apontando para o endpoint local do LocalStack
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve